name: Sandbox Deployment

on:
  issue_comment:
    types: [created]
  push:
    branches:
      - master

jobs:
  trigger-sandbox-deployment:
    name: Trigger Vercel Sandbox Deployment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    if: (contains(github.event.comment.body, 'deploy:sandbox') && github.event.issue.pull_request) || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    steps:
      - name: Get the source branch name
        id: source_branch
        uses: actions/github-script@v6
        with:
          script: |
            if (context.eventName == 'push' && context.ref == 'refs/heads/master') {
              console.log(`Source branch name is: master`);
              return 'master';
            } else {
              const issue_number = context.issue.number;
              const repository = context.repo;
              const pr = await github.rest.pulls.get({
                owner: repository.owner,
                repo: repository.repo,
                pull_number: issue_number
              });
              console.log(`Source branch name is: ${pr.data.head.ref}`);
              return pr.data.head.ref;
            }

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Update sandbox branch"
        run: |
          export SOURCE_BRANCH_NAME=${{ steps.source_branch.outputs.result }}
          echo "Merging $SOURCE_BRANCH_NAME into sandbox and pushing"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout $SOURCE_BRANCH_NAME
          git checkout sandbox
          git merge $SOURCE_BRANCH_NAME
          git push origin sandbox
